// Programmatic route pages: /rutas/[origin-city-slug]-[festival-slug]
// Each page targets long-tail queries like:
//   "carpooling Madrid Mad Cool", "viaje compartido Valencia Primavera Sound"
//
// Data is derived 100% from festivalLandings.ts — no duplication.
// A RouteLanding is generated for every (originCity × festival) pair,
// subject to the distance gate (see DISTANCE GATE section below).

import { FESTIVAL_LANDINGS, type FestivalLanding, type OriginCity } from "./festivalLandings";
import { CITY_LANDINGS } from "./cityLandings";

export interface RouteLanding {
  /** URL-safe slug: "madrid-mad-cool" */
  slug: string;
  originCity: string;
  originCitySlug: string;
  festival: FestivalLanding;
  originData: OriginCity;
}

function cityToSlug(city: string): string {
  return city
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// ─────────────────────────────────────────────────────────────────────────────
// Distance gate (relaxed 2026-05-23 — now secondary to popularity gate below)
// ─────────────────────────────────────────────────────────────────────────────
// Hard upper bound for sanity: any combination >900 km straight (~1,200 km road,
// ~13 h driving) is implausible for single-leg carpooling regardless of demand
// signal. The primary filter is now POPULARITY_GATE (see below).
const MAX_ROUTE_STRAIGHT_KM = 900;

// ─────────────────────────────────────────────────────────────────────────────
// Popularity gate (introduced 2026-05-23) — anti Scaled Content Abuse
// ─────────────────────────────────────────────────────────────────────────────
// Google Core Update March 2026 penalizes "Scaled Content Abuse" — programmatic
// pages generated by permutation where only a keyword changes. With 199
// festivals × 116 cities, the unbounded set is ~18,120 routes; ~73 % of those
// have ZERO real demand signal (e.g. Ourense→Mad Cool, Lugo→Festival de Jerez).
//
// A route is now kept only if AT LEAST ONE popularity signal is present:
//   (A) Curated: the originCity is declared in festivalLandings.ts.originCities
//   (B) Big origin: city population ≥ 200,000 (top 36 Spanish cities)
//   (C) Tier-1 festival: top 16 festivals by traffic / brand recognition
//
// Routes failing all three signals are excluded — they had no realistic chance
// of receiving organic search traffic and only diluted site-wide quality.
// Expected final count: ~4,893 routes (vs 18,120 unfiltered), well below the
// 20,000-asset Cloudflare Workers Free plan manifest limit.
//
// Verified 2026-05-23 via scripts/_measure-route-popularity.mjs.

// Top-36 Spanish cities by population (INE 2024, ≥200k inhabitants).
// Slugs match cityLandings.ts canonical slugs.
const BIG_ORIGIN_SLUGS = new Set<string>([
  "madrid", "barcelona", "valencia", "sevilla", "zaragoza", "malaga",
  "murcia", "palma", "las-palmas-de-gran-canaria", "bilbao", "alicante",
  "cordoba", "valladolid", "vigo", "gijon", "vitoria-gasteiz", "a-coruna",
  "granada", "elche", "oviedo", "santa-cruz-de-tenerife", "badalona",
  "cartagena", "terrassa", "jerez-de-la-frontera", "sabadell", "mostoles",
  "alcala-de-henares", "pamplona", "fuenlabrada", "almeria", "leganes",
  "san-sebastian", "donostia-san-sebastian", "getafe", "burgos", "santander",
]);

// Tier-1 festivals: top 16 by demand / brand. Slugs match festivalLandings.ts.
const TIER1_FESTIVAL_SLUGS = new Set<string>([
  "mad-cool", "primavera-sound", "sonar", "fib", "bbk-live",
  "resurrection-fest", "arenal-sound", "medusa-festival", "vina-rock",
  "cala-mijas", "o-son-do-camino", "cruilla", "low-festival", "boombastic",
  "tomavistas", "rio-babel",
]);

// Override list for routes we want to keep even without popularity signals
// (e.g. emerging festival from a small origin city we want to seed).
const POPULARITY_GATE_ALLOWLIST = new Set<string>([
  // Format: `${citySlug}|${festivalSlug}` — currently empty.
]);

function hasPopularitySignal(originSlug: string, festivalSlug: string, isCurated: boolean): boolean {
  if (POPULARITY_GATE_ALLOWLIST.has(`${originSlug}|${festivalSlug}`)) return true;
  if (isCurated) return true;
  if (BIG_ORIGIN_SLUGS.has(originSlug)) return true;
  if (TIER1_FESTIVAL_SLUGS.has(festivalSlug)) return true;
  return false;
}

// CityLanding slugs known to be on islands (no road link to mainland).
const ISLAND_CITY_SLUGS = new Set<string>([
  "palma",                      // Mallorca
  "ibiza",                      // Ibiza
  "las-palmas-de-gran-canaria", // Gran Canaria
  "santa-cruz-de-tenerife",     // Tenerife
]);

// FestivalLanding slugs known to be on islands.
const ISLAND_FESTIVAL_SLUGS = new Set<string>([
  "mallorca-live-festival", // Mallorca (Baleares)
  "granca-live-fest",       // Gran Canaria (Canarias)
]);

// Same-archipelago island↔island pairs are kept; cross-archipelago is filtered.
const ARCHIPELAGO_OF = new Map<string, "baleares" | "canarias">([
  ["palma", "baleares"],
  ["ibiza", "baleares"],
  ["mallorca-live-festival", "baleares"],
  ["las-palmas-de-gran-canaria", "canarias"],
  ["santa-cruz-de-tenerife", "canarias"],
  ["granca-live-fest", "canarias"],
]);

const DISTANCE_GATE_ALLOWLIST = new Set<string>([
  // Add `${citySlug}|${festivalSlug}` entries here to override the filter.
  // (empty for now)
]);

function isCrossSeaCombo(originCitySlug: string, festivalSlug: string): boolean {
  const cityIsIsland = ISLAND_CITY_SLUGS.has(originCitySlug);
  const festivalIsIsland = ISLAND_FESTIVAL_SLUGS.has(festivalSlug);
  if (!cityIsIsland && !festivalIsIsland) return false;
  if (cityIsIsland && festivalIsIsland) {
    return ARCHIPELAGO_OF.get(originCitySlug) !== ARCHIPELAGO_OF.get(festivalSlug);
  }
  return true;
}

function haversineKm(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) *
      Math.sin(dLng / 2);
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function buildRoutes(): RouteLanding[] {
  const routes: RouteLanding[] = [];
  for (const festival of FESTIVAL_LANDINGS) {
    // Merge explicit originCities from the festival with the canonical CITY_LANDINGS
    const seen = new Set<string>();
    // First, add the explicit originCities (trusted data — always pass the
    // popularity gate via isCurated=true). Still subject to cross-sea and
    // distance sanity bounds.
    for (const oc of festival.originCities) {
      const originSlug = cityToSlug(oc.city);
      seen.add(originSlug);
      const pairKey = `${originSlug}|${festival.slug}`;
      if (!DISTANCE_GATE_ALLOWLIST.has(pairKey)) {
        if (isCrossSeaCombo(originSlug, festival.slug)) continue;
        // OriginCity has no lat/lng — look up CITY_LANDINGS where available.
        const cityLanding = CITY_LANDINGS.find(
          (c) => cityToSlug(c.display || c.city) === originSlug,
        );
        if (cityLanding) {
          const straightKm = haversineKm(cityLanding.lat, cityLanding.lng, festival.lat, festival.lng);
          if (straightKm > MAX_ROUTE_STRAIGHT_KM) continue;
        }
      }
      // Popularity gate: curated routes always pass.
      if (!hasPopularitySignal(originSlug, festival.slug, /* isCurated */ true)) continue;
      routes.push({
        slug: `${originSlug}-${festival.slug}`,
        originCity: oc.city,
        originCitySlug: originSlug,
        festival,
        originData: oc,
      });
    }

    // Then, augment with canonical city landings to scale the number of routes.
    // We only add cities not already present in the festival originCities to avoid duplicates.
    for (const c of CITY_LANDINGS) {
      // Use the canonical slug from cityLandings (not re-derived from display),
      // so route slugs stay consistent with seoOverrides and sitemap entries.
      const originSlug = c.slug;
      if (seen.has(originSlug)) continue;
      seen.add(originSlug);
      const pairKey = `${originSlug}|${festival.slug}`;
      // Distance gate: skip cross-sea combos unless explicitly allowlisted.
      if (!DISTANCE_GATE_ALLOWLIST.has(pairKey) && isCrossSeaCombo(originSlug, festival.slug)) {
        continue;
      }
      // Estimate distance using Haversine formula from city coords to festival coords.
      const straightKm = haversineKm(c.lat, c.lng, festival.lat, festival.lng);
      // Sanity bound: drop implausibly-long single-leg drives.
      if (straightKm > MAX_ROUTE_STRAIGHT_KM && !DISTANCE_GATE_ALLOWLIST.has(pairKey)) {
        continue;
      }
      // Popularity gate: skip routes with no real demand signal (anti Scaled
      // Content Abuse). Augment-loop routes are NOT curated by definition.
      if (!hasPopularitySignal(originSlug, festival.slug, /* isCurated */ false)) continue;
      // Road distance ≈ straight-line × 1.35 for Spain
      const km = Math.round(straightKm * 1.35);
      // Driving time at ~90 km/h average (motorways + urban)
      const hours = km / 90;
      const h = Math.floor(hours);
      const m = Math.round((hours - h) * 60);
      const drivingTime = h > 0 ? `${h}h ${m > 0 ? m + "min" : ""}`.trim() : `${m}min`;
      // Price estimate: €0.04/km per seat (fuel + wear ÷ 3 passengers)
      const priceMin = Math.max(3, Math.round(km * 0.04));
      const priceMax = Math.max(5, Math.round(km * 0.06));
      const concertRideRange = `${priceMin}–${priceMax} €/asiento`;
      const oc: OriginCity = {
        city: c.display || c.city,
        km,
        drivingTime,
        concertRideRange,
      };
      routes.push({
        slug: `${originSlug}-${festival.slug}`,
        originCity: oc.city,
        originCitySlug: originSlug,
        festival,
        originData: oc,
      });
    }
  }
  return routes;
}

export const ROUTE_LANDINGS: RouteLanding[] = buildRoutes();
export const ROUTE_LANDINGS_BY_SLUG: Record<string, RouteLanding> = Object.fromEntries(
  ROUTE_LANDINGS.map((r) => [r.slug, r]),
);
export const ROUTE_SLUGS = ROUTE_LANDINGS.map((r) => r.slug);

// Exported for the legacy-redirects generator (apps/api/src/index.ts) so that
// pre-2026-05-23 routes that no longer pass the popularity gate redirect to
// their festival landing instead of returning 404.
export { BIG_ORIGIN_SLUGS, TIER1_FESTIVAL_SLUGS, hasPopularitySignal };
